# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-02 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accordion',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_accordion_accordion', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(default='', max_length=200, verbose_name='title')),
                ('custom_classes', models.CharField(blank=True, max_length=200, verbose_name='custom classes')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='AccordionEntry',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_accordion_accordionentry', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(default='', max_length=200, verbose_name='title')),
                ('custom_classes', models.CharField(blank=True, max_length=200, verbose_name='custom classes')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
